version: '3.8'

services:
  blocksci:
    build: .
    container_name: blocksci_container
    volumes:
      - blocksci_data:/data
    environment:
      - TZ=Etc/UTC
    ulimits:
      nofile:
        soft: 64000
        hard: 64000
    command: /bin/bash

volumes:
  blocksci_data:
