version: '3.8'

services:
  blocksci:
    build: .
    container_name: blocksci_container
    volumes:
      - /home/isslab/.bitcoin:/bitcoin_data
    environment:
      - TZ=Etc/UTC
    ulimits:
      nofile:
        soft: 64000
        hard: 64000
    command: >
      /bin/bash -c "
      blocksci_parser /bitcoin_data/blocksci.conf generate-config bitcoin /bitcoin_data --disk /bitcoin_data && 
      blocksci_parser /bitcoin_data/blocksci.conf update &&
      bash
      "
